create table links (
	id int GENERATED BY DEFAULT AS IDENTITY,
	title text,
	description text,
	image_url text,
	keywords text [],
	url text not null unique,
	source_file text not null,
	created_at timestamp with time zone default current_timestamp,
	crawl_status text default 'pending' check (crawl_status in ('pending', 'success', 'failed')),
	crawled_at timestamp with time zone,
	markdown_content text,
	crawl_error text,
	summary_status text default 'pending' check (
		summary_status in ('pending', 'success', 'failed')
	),
	summary text,
	summary_error text,
	summary_created_at timestamp with time zone,
	summary_updated_at timestamp with time zone,
	primary key (id)
);