create table "public"."links" (
    "id" integer generated by default as identity not null,
    "url" text not null,
    "source_file" text not null,
    "created_at" timestamp with time zone default CURRENT_TIMESTAMP,
    "crawl_status" text default 'pending'::text,
    "crawled_at" timestamp with time zone,
    "markdown_content" text,
    "crawl_error" text,
    "summary_status" text default 'pending'::text,
    "summary" text,
    "summary_error" text,
    "summary_created_at" timestamp with time zone,
    "summary_updated_at" timestamp with time zone
);


CREATE UNIQUE INDEX links_pkey ON public.links USING btree (id);

CREATE UNIQUE INDEX links_url_key ON public.links USING btree (url);

alter table "public"."links" add constraint "links_pkey" PRIMARY KEY using index "links_pkey";

alter table "public"."links" add constraint "links_crawl_status_check" CHECK ((crawl_status = ANY (ARRAY['pending'::text, 'success'::text, 'failed'::text]))) not valid;

alter table "public"."links" validate constraint "links_crawl_status_check";

alter table "public"."links" add constraint "links_summary_status_check" CHECK ((summary_status = ANY (ARRAY['pending'::text, 'success'::text, 'failed'::text]))) not valid;

alter table "public"."links" validate constraint "links_summary_status_check";

alter table "public"."links" add constraint "links_url_key" UNIQUE using index "links_url_key";

grant delete on table "public"."links" to "anon";

grant insert on table "public"."links" to "anon";

grant references on table "public"."links" to "anon";

grant select on table "public"."links" to "anon";

grant trigger on table "public"."links" to "anon";

grant truncate on table "public"."links" to "anon";

grant update on table "public"."links" to "anon";

grant delete on table "public"."links" to "authenticated";

grant insert on table "public"."links" to "authenticated";

grant references on table "public"."links" to "authenticated";

grant select on table "public"."links" to "authenticated";

grant trigger on table "public"."links" to "authenticated";

grant truncate on table "public"."links" to "authenticated";

grant update on table "public"."links" to "authenticated";

grant delete on table "public"."links" to "service_role";

grant insert on table "public"."links" to "service_role";

grant references on table "public"."links" to "service_role";

grant select on table "public"."links" to "service_role";

grant trigger on table "public"."links" to "service_role";

grant truncate on table "public"."links" to "service_role";

grant update on table "public"."links" to "service_role";


